### ISSUE TITLE
[feature request] add day of the week

### ISSUE THREAD

**Issue by gbdomubpkm** [jittopjose/DoToDo#1]
Please add the day of the week (Mo, Tu, We...)  with the due date. Completely lost without.
Thank you.

**Comment by gbdomubpkm** [comment]
Thank you for the work 👍

**Comment by jittopjose** [comment]
At the moment, Ionic date picker does not support adding day of week.  But we can display the day of week after selection. That is what I have implemented now. 
In the future, probably I will have to look for a better date picker control

**Comment by gbdomubpkm** [comment]
Indeed, to be improved as much as possible.  I'm reopening.

I can see on the main screen at the bottom: < Today >.  Can you display < Today 12/07/2020 >  ?
(my format, french, is already taken into account on this page because I see, after  the page  < Tomorrow >  ,  the page 14/07/2020) : but when i edit a task i see : Sun, Jul 12 2020.

I hope that it will be possible to see the day of the week on this line at a later date.

**Comment by jittopjose** [comment]
@gbdomubpkm  Thanks for the suggestion. I am thinking of setting the date format to  Sun, Jul 12 2020 across the application at the moment as the localization is not yet implemented.

**Comment by jittopjose** [comment]
@gbdomubpkm A new version is uploaded to open-store. Is this the change you expect?. Kindly verify and let me know

**Comment by gbdomubpkm** [comment]
Thank you!  In my opinion, this suits very well and clarifies the presentation.  For me, if nothing is added, the request can be closed.
It is now the other request (several lines...) that will make the app really operational i think.

**Comment by jittopjose** [comment]
@gbdomubpkm Thanks..
The work to bring a description field for task is in progress.
